/** Declaration file generated by dts-gen */

declare function omit_deep_lodash(input: any, props: any, ...args: any[]): any;

declare module "omit-deep-lodash" {
  export default omit_deep_lodash;
}
