version: "3.6"

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  mqtt-data:
    driver: local
  influx-data:
    driver: local
  chronograf-data:
    driver: local
  app-gems:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
       - postgres-data:/var/lib/postgresql/data:delegated
    restart: on-failure
    environment:
      POSTGRES_USER: ifm
      POSTGRES_DB: ifm

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 3001:80
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bigclear.farm
      PGADMIN_DEFAULT_PASSWORD: bigclear1

  redis:
    image: redis:3.2.4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis:delegated
    restart: on-failure
    command: redis-server --appendonly yes

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: on-failure
    volumes:
      - ./config/mosquitto.dev.conf:/mosquitto/config/mosquitto.conf:delegated
      - mqtt-data:/mosquitto/data:delegated

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influx-data:/var/lib/influxdb
    restart: on-failure
    environment:
      INFLUXDB_DB: ifm_development
      INFLUXDB_HTTP_LOG_ENABLED: "false"
      INFLUXDB_LOGGING_LEVEL: "warn"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: bigclear1

  chronograf:
    image: chronograf:1.3.8
    volumes:
      - chronograf-data:/var/lib/chronograf
    ports:
      - 8888:8888
    depends_on:
      - influxdb
    restart: on-failure
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOG_LEVEL: error

  jobs: &app_base
    build:
      context: .
      args:
        bundle_without: ""
    command: bundle exec sidekiq -c 25 -q default
    restart: on-failure
    volumes:
      - .:/app:delegated
      - ~/Code:/root/Code:delegated # useful for linking other gems
      - app-gems:/usr/local/bundle:delegated
    depends_on:
      - postgres
      - redis
      - influxdb
      - mqtt
    logging:
      options:
        max-size: "200k"
        max-file: "3"
    environment: &app_environment
      DEV_DATABASE_URL: postgres://ifm@postgres/ifm_development
      TEST_DATABASE_URL: postgres://ifm@postgres/ifm_test
      DB_POOL: 30
      INFLUXDB_URL: http://influxdb:8086/ifm_development
      RELOAD_CODE: 'false'
      REDIS_URL: redis://redis:6379/1
      MQTT_URL: mqtt://mqtt:1883
      RACK_ENV: development
      RAILS_ENV: development
      NODE_ENV: development

  web:
    <<: *app_base
    image: integrated-farm-manager/ifm
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - 3000:3000 # rails server
      - 9229:9229 # node debugger
    environment:
      <<: *app_environment
      DB_POOL: 5
      RELOAD_CODE: 'true'

  webpack-dev-server:
    <<: *app_base
    command: bin/webpack-dev-server
    ports:
      - 3035:3035

  production-mqtt-mirror:
    <<: *app_base
    command: bin/rake mqtt:mirror_production[sensors/#]
    environment:
      <<: *app_environment
      PRODUCTION_MQTT_URL: mqtt://peacxxic:rfLeHoJBFMAp@m10.cloudmqtt.com:13796
