version: '3'

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  mqtt-data:
    driver: local
  influx-data:
    driver: local
  app-gems:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
       - postgres-data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: ifm
      POSTGRES_DB: ifm

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 3001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bigclear.farm
      PGADMIN_DEFAULT_PASSWORD: bigclear1

  redis:
    image: redis:3.2.4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis:delegated
    command: redis-server --appendonly yes

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mqtt-data:/mosquitto/data:delegated

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influx-data:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: bigclear1

  web: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    volumes:
      - .:/app:delegated
      - ~/Code:/root/Code:delegated # useful for linking other gems
      - app-gems:/usr/local/bundle:delegated
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://ifm@postgres/ifm_development
      REDIS_URL: redis://redis:6379/1
      MQTT_URL: mqtt://peacxxic:rfLeHoJBFMAp@m10.cloudmqtt.com:13796
      RACK_ENV: development
      RAILS_ENV: development

  webpack-dev-server:
    <<: *app_base
    command: bin/webpack-dev-server
    ports:
      - 3035:3035

  jobs:
    <<: *app_base
    command: sidekiq -c 25 -q default
    ports: []

  # test:
  #   <<: *app_base
  #   command: bin/rails test
  #   ports: []
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://ifm@postgres/ifm_test
  #     REDIS_URL: redis://redis:6379/15
  #     MQTT_URL: mqtt://mqtt
  #     RACK_ENV: test
  #     RAILS_ENV: test
