/** Declaration file generated by dts-gen */

export = omit_deep_lodash;

declare function omit_deep_lodash(input: any, props: any, ...args: any[]): any;

declare namespace omit_deep_lodash {
    const prototype: {
    };

}

