apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-bigclear-farm-production
spec:
  secretName: tls-bigclear-farm-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.berries.fun"
    - "*.app.berries.fun"
  acme:
    config:
    - dns01:
        provider: ifm-clouddns
      domains:
      - "*.berries.fun"
      - "*.app.berries.fun"
