---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: influx-data
  name: influx-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  ports:
  - name: "8086"
    port: 8086
    targetPort: 8086
  selector:
    io.kompose.service: influxdb
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.14.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADMIN_PASSWORD
          value: bigclear1
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_DB
          value: ifm_development
        - name: INFLUXDB_HTTP_LOG_ENABLED
          value: "false"
        - name: INFLUXDB_LOGGING_LEVEL
          value: warn
        image: influxdb
        name: influxdb
        ports:
        - containerPort: 8086
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influx-data
      restartPolicy: Always
      volumes:
      - name: influx-data
        persistentVolumeClaim:
          claimName: influx-data
status: {}
