apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingerss
  annotations:
    kubernetes.io/ingress.global-static-ip-name: web-static-ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: web
          servicePort: 3000
      - path: /chronograph/*
        backend:
          serviceName: chronograph
          servicePort: 8888
