apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fanout
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 2M
    nginx.ingress.kubernetes.io/proxy-body-size: 10M
spec:
  tls:
    - secretName: berries-fun-production
      hosts:
        - chronograf.app.berries.fun
        - influxdb.app.berries.fun
        - app.berries.fun
  rules:
  - host: chronograf.app.berries.fun
    http:
      paths:
        - backend:
            serviceName: chronograf
            servicePort: 8888
  - host: influxdb.app.berries.fun
    http:
      paths:
        - backend:
            serviceName: influxdb
            servicePort: 8086
  - host: app.berries.fun
    http:
      paths:
        - backend:
            serviceName: web
            servicePort: 80
