---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: gce-ssd
  resources:
    requests:
      storage: "8Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    name: api
  selector:
    app: kapacitor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kapacitor
    spec:
      containers:
      - name: kapacitor
        image: "kapacitor:1.5.0-alpine"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 0.1
            memory: 256Mi
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: data
          mountPath: /var/lib/kapacitor
        env:
          - name: KAPACITOR_HOSTNAME
            value: kapacitor
          - name: KAPACITOR_LOGGING_LEVEL
            value: INFO
          - name: KAPACITOR_REPORTING_ENABLED
            value: 'false'
          - name: KAPACITOR_INFLUXDB_0_URLS_0
            value: http://influxdb:8086
          - name: KAPACITOR_INFLUXDB_0_USERNAME
            valueFrom:
              secretKeyRef:
                name: influx-secrets
                key: username
          - name: KAPACITOR_INFLUXDB_0_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influx-secrets
                key: password
          - name: KAPACITOR_KUBERNETES_ENABLED
            value: "true"
          - name: KAPACITOR_KUBERNETES_IN_CLUSTER
            value: "true"
          - name: KAPACITOR_SLACK_0_ENABLED
            value: "true"
          - name: KAPACITOR_SLACK_0_DEFAULT
            value: "true"
          - name: KAPACITOR_SLACK_0_WORKSPACE
            value: "bigclearfarms.slack.com"
          - name: KAPACITOR_SLACK_0_URL
            valueFrom:
              secretKeyRef:
                name: influx-secrets
                key: slack_webhook_url
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kapacitor
