---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt-data-ssd
  name: mqtt-data-ssd
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gce-ssd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt
    spec:
      containers:
      - image: eclipse-mosquitto
        name: mqtt
        # command: ["sleep", "1000000"]
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /mosquitto/data
          name: mqtt-data-ssd
        - mountPath: /mosquitto/config/mosquitto.conf
          name: mosquitto-config
          subPath: mosquitto.conf
          readOnly: true
        - mountPath: "/mosquitto/mosquitto_passwd"
          name: mosquitto-passwd
          subPath: mosquitto_passwd
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: mqtt-data-ssd
        persistentVolumeClaim:
          claimName: mqtt-data-ssd
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
          items:
          - key: mosquitto.conf
            path: mosquitto.conf
      - name: mosquitto-passwd
        secret:
          secretName: mqtt-credentials
          items:
          - key: mosquitto_passwd
            path: mosquitto_passwd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    password_file /mosquitto/mosquitto_passwd
    allow_anonymous false
    persistence true
    persistence_location /mosquitto/data/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mqtt
  name: mqtt
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.app.berries.fun
spec:
  type: LoadBalancer
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    io.kompose.service: mqtt
