apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-bigclear-farm-production
  namespace: ifm-production
spec:
  secretName: tls-bigclear-farm-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.bigclear.farm"
  acme:
    config:
    - dns01:
        provider: ifm-clouddns
      domains:
      - "*.bigclear.farm"
