# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/cci-demo-docker-primary:0.0.2

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
        docker_layer_caching: true

      # build and start docker images
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose --build up -f docker-compose.circle.yml -f ../docker-compose.yml
