version: '3.6'

services:
  web:
    environment:
      CIRCLECI: 'true'
    build:
      args:
        webpack_build: 'true'
  jobs:
    environment:
      CIRCLECI: 'true'
    build:
      args:
        webpack_build: 'true'

  mqtt:
    volumes:
      - mqtt-config:/mosquitto/config

volumes:
  mqtt-config:
