version: '3.6'

services:
  web:
    environment:
      CIRCLECI: 'true'
    build:
      args:
        bundle_without: development test

  jobs:
    environment:
      CIRCLECI: 'true'
    build:
      args:
        bundle_without: development test

  mqtt:
    volumes:
      - mqtt-config:/mosquitto/config

volumes:
  mqtt-config:
