version: '3.6'

services:
  web:
    environment:
      CIRCLECI: 'true'
  web:
    environment:
      CIRCLECI: 'true'

  mqtt:
    volumes:
      - mqtt-config:/mosquitto/config

volumes:
  mqtt-config:
