version: '3.6'

services:
  web:
    environment:
      CIRCLECI: 'true'
    build:
      args:
        # right now the same container is being used for production and testing, so these gems are needed in the container to run tests
        # bundle_without: development test
  web:
    environment:
      CIRCLECI: 'true'
    build:
      args:
        # bundle_without: development test

  mqtt:
    volumes:
      - mqtt-config:/mosquitto/config

volumes:
  mqtt-config:
