version: '3.2'

# Override the containers not needed for testing to exit 0.
services:
  pgadmin:
    command: sh -c "exit 0"
  jobs:
    command: sh -c "exit 0"
  web:
    command: sh -c "exit 0"
  webpack-dev-server:
    command: sh -c "exit 0"
