import gql from "graphql-tag";
import { Query } from "react-apollo";
import { GetDeviceDiscoveryLogs } from "./types";

// This file is fucked up. It is a list of the queries in the application, but it references an autogenerated file, `types.ts`, beside it.
// That file is generated by looking at all the `g ql` tags in this file. You have to write code that won't compile, then run the generator,
// then see if it compiles. A terrible idea I know. Yeesh.
export class GetDeviceDiscoveryLogsQuery extends Query<GetDeviceDiscoveryLogs.Query, GetDeviceDiscoveryLogs.Variables> {
  public static query = gql`
    query getDeviceDiscoveryLogs {
      deviceDiscoveryLogs {
        id
        imageUrl
        dataAddress
        deviceName
        lastSeen
        data
      }
    }
  `;
}
