/* tslint:disable */
/** Generated in 2018-06-07T22:35:02+00:00 */

export type Json = any;

export type DateTime = any;

export interface Query {
  allDeviceDiscoveryLogs?:
    | DeviceDiscoveryLog[]
    | null /** List DeviceDiscoveryLogs */;
}

export interface DeviceDiscoveryLog {
  data?: Json | null;
  deviceClass: string;
  id: string;
  lastSeen: DateTime;
  mqttKey: string;
}

export interface Mutation {
  enlistDevice?: EnlistDevicePayload | null;
}
/** Autogenerated return type of EnlistDevice */
export interface EnlistDevicePayload {
  clientMutationId?:
    | string
    | null /** A unique identifier for the client performing the mutation. */;
  deviceConfiguration?: DeviceConfiguration | null;
  errorMessages: string[];
}

export interface DeviceConfiguration {
  data?: Json | null;
  deviceClass: string;
  humanName: string;
  id: string;
  lastSeen: DateTime;
  macAddress: string;
}
/** Autogenerated input type of EnlistDevice */
export interface EnlistDeviceInput {
  deviceDiscoveryLogId: string;
  clientMutationId?:
    | string
    | null /** A unique identifier for the client performing the mutation. */;
}
export interface AllDeviceDiscoveryLogsQueryArgs {
  dismissed?: boolean | null;
}
export interface EnlistDeviceMutationArgs {
  input: EnlistDeviceInput;
}
export namespace GetAllDeviceDiscoveryLogs {
  export type Variables = {};

  export type Query = {
    __typename?: "Query";
    allDeviceDiscoveryLogs?: AllDeviceDiscoveryLogs[] | null;
  };

  export type AllDeviceDiscoveryLogs = {
    __typename?: "DeviceDiscoveryLog";
    id: string;
    mqttKey: string;
    deviceClass: string;
    lastSeen: DateTime;
    data?: Json | null;
  };
}
