development:
  url: <%= ENV['DEV_DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

test:
  url: <%= ENV['TEST_DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

production:
  url: <%= ENV['DATABASE_URL'] %>
