apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: harry@bigclear.farm
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
        - name: ifm-clouddns
          clouddns:
            serviceAccountSecretRef:
              name: clouddns-service-account
              key: credentials.json
            project: integrated-farm-manager
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: harry@bigclear.farm
    privateKeySecretRef:
      name: letsencrypt-production
    dns01:
      providers:
        - name: ifm-clouddns
          clouddns:
            serviceAccountSecretRef:
              name: clouddns-service-account
              key: credentials.json
            project: integrated-farm-manager
